#ifndef ASSETS_H
#define ASSETS_H
#include "eve.h"
enum Fonts {
    FONT_55W_12PX_A,
    FONT_55W_16PX_AN,
    FONT_55W_18PX_A,
    FONT_55W_21PX_A,
    FONT_55W_30PX_A,
    FONT_65W_64PX_N,
    FONT_65W_84PX_N,
    FONT_75W_19PX_A,
    FONT_75W_29PX_A,
    FONT_75W_39PX_A,
    FONT_65W_40PX_F,
    FONT_65W_40PX_N,
    FONT_65W_30PX_AN,
};

enum Images {
    IMAGE_BTN_PAUSE,
    IMAGE_BTN_RETURN,
    IMAGE_BTN_START,
    IMAGE_CANNATROL,
    IMAGE_COOLCUREMAIN,
    IMAGE_GEARS,
    IMAGE_COOLCUREBOTTOM,
    IMAGE_BTN_RESET,
    IMAGE_BTN_NEXT,
    IMAGE_WHEEL,
    IMAGE_BTN_WIFI,
    IMAGE_BTN_HOME,
    IMAGE_BTN_TEMP,
    IMAGE_BTN_BLUETOOTH,
    IMAGE_BTN_LANG,
    IMAGE_BTN_SUBMIT_ONMDPI,
    IMAGE_BTN_FACTORY_ONMDPI,
};

void load_assets();
void load_wheel();
#endif
